#!/bin/bash
echo "-rwxr--r-- 1 root root 107 Aug 31 15:12 0-current_working_directory                                                                                      

-rwxr--r-- 1 root root  66 Aug 31 16:08 1-listit                                                                                                         

-rwxr--r-- 1 root root  25 Aug 31 16:23 2-bring_me_home                                                                                                  
-rw-r--r-- 1 root root   0 Aug 31 16:40 3-listfilles                                    
-rw-r--r-- 1 root root  35 Aug 31 14:22 README.md"
